### ISSUE TITLE
Broken package import

### ISSUE THREAD

**Issue by ipoerner** [roblillack/revel-generator#2]
The import path in `revel-generator.go` to `github.com/revel/revel/harness` is broken. It can now be found here:

`github.com/revel/cmd/harness`

**Comment by roblillack** [comment]
Hey @ipoerner, based on revel version 0.11.1 that revel-generator has as a dependency, the package should be available: https://github.com/revel/revel/tree/v0.11.1/harness

**Comment by ipoerner** [comment]
True story. I tried fetching the package using `go get` but my version of Revel was a more recent one.
